# Generated by Django 5.2.7 on 2025-10-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_prescription_prescription_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
