# Generated by Django 5.0.6 on 2025-10-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_prescription_is_verified_prescription_verified_at'),
        ('home', '0005_rename_name_doctor_first_name_doctor_last_name'),
    ]

    operations = [
    ]
