# Generated by Django 5.2.7 on 2025-10-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20251009_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, upload_to='audio_recordings/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
    ]
