# Generated by Django 5.2.7 on 2025-10-14 07:14

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_prescription_audio_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
