# Generated by Django 5.2.7 on 2025-10-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_doctor_is_2fa_enabled_doctor_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='otp_secret',
        ),
    ]
