# Generated by Django 5.2.7 on 2025-10-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='consultation_audio/')),
                ('transcribed_text', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, help_text='A short bio for the profile page.'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='professional_details',
            field=models.TextField(blank=True, help_text='Degrees, certifications, etc.'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.audio'),
        ),
    ]
