# Generated by Django 5.0.6 on 2025-10-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_llmaudit'),
        ('home', '0013_patient_allergy_patient_bloodpressure_and_more'),
    ]

    operations = [
    ]
