# Generated by Django 5.2.7 on 2025-10-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20251029_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bloodpressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='previous_medication',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='severity',
        ),
    ]
