# Generated by Django 5.2.7 on 2025-11-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, help_text='Full address of the clinic.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, help_text='Logo for the prescription background.', null=True, upload_to='clinic_logos/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Name of the medical clinic/center.', max_length=255, null=True),
        ),
    ]
