# Generated by Django 5.0.6 on 2025-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_doctor_clinic_address_doctor_clinic_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_pdf',
            field=models.FileField(blank=True, null=True, upload_to='medication_pdfs/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, help_text='Address, Phone, Email (Pipe-separated if using the default form).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_logo',
            field=models.ImageField(blank=True, help_text='Logo for the prescription watermark.', null=True, upload_to='clinic_logos/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Official name of the clinic/practice.', max_length=255, null=True),
        ),
    ]
