# Generated by Django 5.0.6 on 2025-11-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_patient_allergy_patient_medication_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medication_pdf',
        ),
    ]
