# Generated by Django 5.2.3 on 2025-11-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_patient_medication_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_json', models.JSONField(default=dict)),
                ('summary_text', models.TextField(blank=True, help_text='Summary of previous meds/symptoms')),
                ('scan_image', models.ImageField(blank=True, null=True, upload_to='scanned_history/')),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_history', to='home.patient')),
            ],
        ),
    ]
